# Generated by Django 3.1 on 2021-10-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211009_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(default='profiles/default_profile.png', upload_to='profiles/'),
        ),
    ]
