# Generated by Django 3.1 on 2021-10-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211009_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
