# Generated by Django 3.2.7 on 2021-10-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to=''),
        ),
    ]
